config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'

  get 'products/index'
  post 'products/index'

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :discount, inclusion: {in: 0..100}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :price, presence: true

  scope :all_premium, -> {where(premium: true)}

  scope :last_n, ->(cant) {limit(cant)}

  after_destroy :last_product


  def last_product

    Category.all.each do |category|
      if category.products.empty?
        category.destroy
      end
    end

  end


  def precio_final
    dis = self.category.discount
    pric = self.price

    descuento = (pric * dis.to_f)/100

    return pric - descuento

  end

  # before_save :premium_default

  # def premium_default
  #   if self.premium.nil?
  #     self.premium = false
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index

    if params[:buscador].present?
      if params[:filtro_precio].present?
        @products = Product.where("name like ?", "%#{params[:buscador]}%")

        if params[:filtro_precio] == "0..5000"
          @products = Product.where("name like ? and price BETWEEN ? AND ?", "%#{params[:buscador]}%", 0, 5000)
        elsif params[:filtro_precio] == "5001..10000"
          @products = Product.where("name like ? and price BETWEEN ? AND ?", "%#{params[:buscador]}%", 5001, 10000)
        elsif params[:filtro_precio] == "10001..+"
          @products = Product.where("name like ? and price >= ?", "%#{params[:buscador]}%", 10001)
        end

      end
    else
      @products = Product.all
    end




  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<h1>Categories#index</h1>


<br><br>

<table>
  <thead>
    <th>Name</th>
    <th>Discount</th>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.discount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tienda</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified JavaScript -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container"><%= yield %></div>

  </body>
</html>

app/views/products/index.html.erb
<h1>Products#index</h1>

<br>
<%= form_tag(products_index_path) do %>
  <%= label_tag :buscador %>
  <%= text_field_tag :buscador, nil, placeholder: "Buscar nombre" %>
  <%= label_tag :filtro_precio %>
  <%= select_tag :filtro_precio, options_for_select([ "Todos","0..5000", "5001..10000", "10001..+" ], "Todos") %>
  <%= submit_tag "Buscar" %>
<% end -%>



<br><br>

<table>
  <thead>
    <th>Name</th>
    <th>Price</th>
    <th>Category</th>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Lista Productos<span class="sr-only">(current)</span></a></li>
        <li><a href="<%= categories_index_path %>">Lista Categorías</a></li>

      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>